### Generate Graph
POST http://localhost:5000/generate-graph HTTP/1.1
content-type: application/json

{
    "x_data": [1, 2, 3],
    "y_data": [9, 8, 7],
    "graph_title": "Test"
}

### Generate Graph No X Data
POST http://localhost:5000/generate-graph HTTP/1.1
content-type: application/json

{
    "y_data": [9, 8, 7],
    "graph_title": "Test"
}

### Generate Graph No Y Data
POST http://localhost:5000/generate-graph HTTP/1.1
content-type: application/json

{
    "x_data": [9, 8, 7],
    "graph_title": "Test"
}

### Generate Graph No Title Data
POST http://localhost:5000/generate-graph HTTP/1.1
content-type: application/json

{
    "x_data": [1, 2, 3],
    "y_data": [9, 8, 7]
}